### ISSUE TITLE
Error while running object_detection_webcam.py

### ISSUE THREAD

**Issue by jayshah19949596** [anujshah1003/Real_time_Object_detection_TF#1]
Traceback (most recent call last):
  File "C:/Users/jaysh/Downloads/Real_time_Object_detection_TF-master/object_recognition_detection/object_detection_webcam.py", line 69, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "C:\Users\jaysh\Downloads\Real_time_Object_detection_TF-master\object_recognition_detection\utils\label_map_util.py", line 120, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 472, in Merge
    text.split('\n'),
TypeError: a bytes-like object is required, not 'str'

**Comment by cringyman** [comment]
i have the same problem
